name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: '31.0.0'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Prepare Cordova project
        working-directory: cordova-app
        run: |
          cordova plugin add phonegap-plugin-push --variable SENDER_ID="${{ secrets.SENDER_ID }}"
          cordova platform add android

      - name: Build Android APK (Release)
        working-directory: cordova-app
        run: cordova build android --release

      - name: List debug & release APKs
        run: |
          echo "Debug APKs:"
          ls -1 cordova-app/platforms/android/app/build/outputs/apk/debug || true
          echo "Release APKs:"
          ls -1 cordova-app/platforms/android/app/build/outputs/apk/release || true

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-reminder-apk
          path: |
            cordova-app/platforms/android/app/build/outputs/apk/debug/*.apk
            cordova-app/platforms/android/app/build/outputs/apk/release/*.apk
